#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { execSync } from 'node:child_process'
import fg from 'fast-glob'
import { minify } from 'html-minifier-terser'

async function minifyOne(file) {
    console.log(`Processing ${file}...`)
    let content = fs.readFileSync(file, 'utf8')

    // 1. Minify PHP (if present)
    // We use php -w to strip comments and whitespace from PHP blocks.
    // This requires PHP to be installed and in the PATH.
    if (file.endsWith('.phtml') || file.endsWith('.php') || file.endsWith('.shtml') || content.includes('<?php')) {
        try {
            // Create a temp file to run php -w on
            const tempFile = file + '.temp.php'
            fs.writeFileSync(tempFile, content)

            // Run php -w
            // -w: Display source with stripped comments and whitespace.
            // We capture stdout.
            const phpMinified = execSync(`php -w "${tempFile}"`, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })

            if (phpMinified) {
                content = phpMinified
            }

            // Clean up temp file
            if (fs.existsSync(tempFile)) {
                fs.unlinkSync(tempFile)
            }
        } catch (e) {
            console.warn(`Warning: Failed to minify PHP in ${file}. Continuing with HTML minification only. Error: ${e.message}`)
            // Clean up temp file if it exists
            const tempFile = file + '.temp.php'
            if (fs.existsSync(tempFile)) {
                fs.unlinkSync(tempFile)
            }
        }
    }

    // 2. Minify HTML/CSS/JS
    try {
        const result = await minify(content, {
            collapseWhitespace: true,
            removeComments: true,
            minifyCSS: true,
            minifyJS: true,
            ignoreCustomFragments: [ /<\?php[\s\S]*?\?>/ ], // Ignore PHP blocks so html-minifier doesn't mangle them
            keepClosingSlash: true,
            caseSensitive: true,
            includeAutoGeneratedTags: false // Prevent inserting tags that might break PHP structure
        })

        fs.writeFileSync(file, result, 'utf8')
        console.log(`Minified: ${file}`)
    } catch (e) {
        console.error(`Error minifying HTML in ${file}:`, e)
    }
}

async function run() {
    const args = process.argv.slice(2);
    const inputDirs = [];

    for (let i = 0; i < args.length; i++) {
        if (args[i] === '--inputDir') {
            if (i + 1 < args.length) {
                inputDirs.push(args[i + 1]);
                i++;
            }
        }
    }

    if (inputDirs.length === 0) {
        console.log('No input directories specified. Use --inputDir <path>. Defaulting to www/dist for backward compatibility if needed, or exiting.');
        // For safety, let's require the argument as requested.
        console.error('Error: No input directories specified. Usage: htm-minify --inputDir <path> [--inputDir <path> ...]');
        process.exit(1);
    }

    const patterns = inputDirs.map(dir => {
        // Normalize path separators to forward slashes for fast-glob
        const cleanDir = dir.replace(/\\/g, '/').replace(/\/$/, '');
        return `${cleanDir}/**/*.{html,phtml,htm,shtml}`;
    });

    console.log(`Searching for files in: ${inputDirs.join(', ')}`);

    // Look for html, phtml, htm, shtml in specified directories
    const files = await fg(patterns);

    if (files.length === 0) {
        console.log('No HTML/PHTML files found to minify.')
        return
    }

    for (const file of files) {
        await minifyOne(file)
    }
}

try {
    await run()
} catch (error) {
    console.error(error)
    process.exitCode = 1
}
